Commit #3.
JuanMiChee/FlashEnglishCards pull request #1
Opened 2023-11-11 04:44 UTC by JuanMiChee

<H3>**Add new card to the list feature:**</H3>
Now the entire implementation of adding a new card to the list is done, including its storage, and management with view and viewModel correctly, i added a view for this action, where we can write the name of the new cell we want to add.

<H3>- I also corrected some error just as: -</H3>
1. Using the actual object, instead of its abstraction at *viewModel.dependencies*
2. Implementation of build function for important views
3. Moving annoying styles to its very own folder, so we can use them without repeating them every single time we need (Buttons for example).
 4.Dividing huge views, into segments, easier to read

<H1>***Evidence:**</H1>

<video src="Uploading Grabación de pantalla 2023-11-10 a la(s) 11.23.20 p. m..mov…" height="600"/>

2023-11-11 04:58 UTC, JuanMiChee commented
This Pr is looking good, well documented, and well written. There is a detail i dont really like tho, you are uploading view changes, with bussines and storage changes, try to split your changes better next time. Something like this:

1. Create AddNewCardFeatureBranch
2. Create another branch from it, called ViewModelChances, so you can make all of your changes in there, so it can be checked by your team easier, and not make us read the whole thing, just makes us read "Hey, this this and that uploaded at viewModel"
3. Continue creating branches like this, one for view changes, one for UI Correcting, another for storage, etc etc, this way will be a lot easier to read for everybody, and your work will be very well organized.
4. once you finish you work with a branch, make a PR to the main one "AddNewCardFeatureBranch" in this case. and once you finish all of the branches and work on them, you can make the PR to develop

I hope you take this as a recomendation and not as a harassment, you bozo. Greetings <3

2023-11-12 16:52 UTC, angelbetancourt requested changes
Just some minot comments

2023-11-12 16:52 UTC, angelbetancourt commented on FlashEnglishCards/Storage/MainStorage.swift
> +            if let encodedFlashCardArray = try? encoder.encode(arrayToSave) {
Make this function throwable and just try here

2023-11-12 16:52 UTC, angelbetancourt commented on FlashEnglishCards/Storage/MainStorage.swift
> +                defaults.set(encodedFlashCardArray, forKey: "flashCardsArray")
```suggestion
                defaults.set(encodedFlashCardArray, forKey: .cards)
```

2023-11-12 16:52 UTC, angelbetancourt commented on FlashEnglishCards/ViewBuilders/HomeViewBuilder.swift
> +        return HomeView(viewModel: HomeViewViewModel(dependencies: HomeViewViewModel.Dependencies(getCards: GetCardsUseCase(storage: storage), saveCards: SaveNewCardUseCase(storage: storage))))
```suggestion
       .init(viewModel: .init(dependencies: .init(getCards: getCards, saveCards: saveCargs)))
```

2023-11-12 16:52 UTC, angelbetancourt commented on FlashEnglishCards/Views/HomeView.swift
> +    @ObservedObject var viewModel: HomeViewViewModel
```suggestion
    @StateObject var viewModel: HomeViewViewModel
```

2023-11-12 16:52 UTC, angelbetancourt commented on FlashEnglishCards/Views/HomeView.swift
> +                    viewModel.isSheetPresented = true
```suggestion
                    viewModel.handleAdd()
```

2023-11-12 16:52 UTC, angelbetancourt commented on FlashEnglishCards/Views/HomeView.swift
> +                text: $viewModel.sheetText
```suggestion
                text: $viewModel.newCardTitle
```

2023-11-14 20:38 UTC, merged